import type { ReactNode } from 'react'
export const PHONE='tel:02462429999', PHONE_TEXT='0246 242 99 99', WA='https://wa.me/902462429999?text=Merhaba%2C%20bilgi%20almak%20istiyorum.'
export function PageHero({eyebrow,title,lead,crumbs=[],side,tone='light'}:{eyebrow:string;title:ReactNode;lead:string;crumbs?:string[];side?:ReactNode;tone?:'light'|'dark'}){return <section className={`page-hero ${tone==='dark'?'page-hero-dark':''}`}><div className="container"><nav className="crumbs" aria-label="Sayfa yolu"><a href="/">Ana sayfa</a>{crumbs.map((c,i)=><span key={c}><i>/</i>{i===crumbs.length-1?<span aria-current="page">{c}</span>:<span>{c}</span>}</span>)}</nav><div className="page-hero-grid"><div><div className="eyebrow"><span className="eyebrow-dot"/>{eyebrow}</div><h1>{title}</h1><p className="page-lead">{lead}</p><div className="hero-actions"><a className="button button-primary" href={PHONE}>Hemen arayın <span className="button-phone">{PHONE_TEXT}</span></a><a className="button button-quiet" href={WA} target="_blank" rel="noreferrer">WhatsApp’tan yazın <span>↗</span></a></div></div>{side&&<div className="page-hero-side">{side}</div>}</div></div></section>}
export function SectionHead({eyebrow,title,copy,light=false}:{eyebrow:string;title:string;copy?:string;light?:boolean}){return <div className={`section-head ${light?'section-head-light':''}`}><div className="eyebrow"><span className="eyebrow-dot"/>{eyebrow}</div><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function ContactBand({title='Bir fiyat sorun, birlikte planlayalım.',copy='Telefonla arayın ya da WhatsApp’tan hizmet ve adres bilgilerinizi gönderin.'}:{title?:string;copy?:string}){return <section className="contact-band"><div className="container contact-band-inner"><div><div className="eyebrow eyebrow-light"><span className="eyebrow-dot"/>İPEK HALI YIKAMA · ISPARTA</div><h2>{title}</h2><p>{copy}</p></div><div className="contact-band-actions"><a className="button button-white" href={PHONE}>{PHONE_TEXT}</a><a className="button button-whatsapp" href={WA} target="_blank" rel="noreferrer">WhatsApp’tan yazın ↗</a></div></div></section>}
export function Steps({items}:{items:{title:string;copy:string}[]}){return <div className="steps">{items.map((s,i)=><article className="step" key={s.title}><span className="step-no">0{i+1}</span><div><h3>{s.title}</h3><p>{s.copy}</p></div></article>)}</div>}
export function FaqRows({items}:{items:[string,string][]}){return <div className="faq-list">{items.map(([q,a])=><details key={q} className="faq-row"><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div>}
export function PriceNote({title='Halı yıkama',price='130',unit='TL / m²',note='6 m² ve altı siparişlerde minimum ücret 780 TL.'}:{title?:string;price?:string;unit?:string;note?:string}){return <div className="price-note"><span className="price-note-label">{title}</span><strong>{price}<small> {unit}</small></strong><p>{note}</p></div>}
export function FeatureRows({items}:{items:{title:string;copy:string;mark?:string}[]}){return <div className="feature-rows">{items.map((x,i)=><article className="feature-row" key={x.title}><span className="feature-mark">{x.mark??String(i+1).padStart(2,'0')}</span><div><h3>{x.title}</h3><p>{x.copy}</p></div><span className="feature-arrow">↗</span></article>)}</div>}

const carpetStages=[
 {title:'Tür ve durum kontrolü',copy:'Halı türü, dokusu ve varsa özel leke bilgisi değerlendirilir.'},
 {title:'Toz alma',copy:'Yıkama öncesi gevşek toz ve kir uzaklaştırılır.'},
 {title:'Yıkama ve durulama',copy:'Halıya uygun yıkama uygulanır, ardından durulanır.'},
 {title:'Kurutma ve son kontrol',copy:'Kurutma sonrası halı teslimat öncesinde kontrol edilir.'},
 {title:'Teslimat',copy:'Temiz halı adresinize teslim edilmek üzere hazırlanır.'},
]
export function CarpetStages(){return <div className="carpet-stages" aria-label="Halı yıkama aşamaları">{carpetStages.map((stage,i)=><article className="carpet-stage" key={stage.title}><div className={`stage-art stage-art-${i+1}`} aria-hidden="true"><svg viewBox="0 0 80 80" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{i===0&&<><path d="M20 18h40v44H20z"/><path d="M27 27h26M27 35h18M27 48l6 6 15-16"/><circle cx="56" cy="55" r="8"/></>}{i===1&&<><path d="M17 55h46M23 48l7-16h20l8 16"/><path d="M30 32l5-8h12l4 8"/><path d="M27 59v5m27-5v5"/><circle className="stage-dust" cx="20" cy="25" r="2"/><circle className="stage-dust" cx="58" cy="20" r="2"/><circle className="stage-dust" cx="64" cy="31" r="1.5"/></>}{i===2&&<><path d="M18 47h44"/><path d="M25 43V29h30v14"/><path d="M29 29V20h22v9"/><path className="stage-brush" d="M28 43v8m7-8v8m7-8v8m7-8v8"/><path className="stage-water" d="M21 56c4-5 8 5 12 0s8 5 12 0 8 5 13 0"/><path d="M63 19c0 4-3 6-3 9a3 3 0 006 0c0-3-3-5-3-9z"/></>}{i===3&&<><path d="M20 19h40v43H20z"/><path d="M27 26h26v28H27z"/><path d="M31 48c4-8 7 4 11-4s7 4 11-4"/><path d="M30 59l6 5 14-13"/><path d="M20 14h40"/></>}{i===4&&<><path d="M18 35h32v22H18z"/><path d="M50 42h9l7 8v7H50z"/><circle cx="29" cy="59" r="4"/><circle cx="56" cy="59" r="4"/><path d="M22 40h23M24 45h19"/><path d="M60 21v11m-5-6 5 6 5-6"/></>}</svg></div><span className="stage-number">0{i+1}</span><h3>{stage.title}</h3><p>{stage.copy}</p></article>)}</div>}
