import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
import { ContactBand, CarpetStages, FaqRows, PHONE, WA, SectionHead } from '../components/site-ui'
import { VideoGallery, photos, servicePhoto } from '../components/site-media'
import { ServiceAreaMap } from '../components/service-area-map'
export const Route=createFileRoute('/')({head:()=>({meta:[{title:'Isparta Halı Yıkama | İpek Halı Yıkama · Ücretsiz Servis'},{name:'description',content:'Isparta’da halı yıkama 130 TL/m², minimum ücret 780 TL. Ücretsiz halı alım ve teslimat; koltuk, perde ve yorgan yıkama. 0246 242 99 99.'},{property:'og:title',content:'İpek Halı Yıkama · Isparta'},{property:'og:description',content:'Fiyatı açık, servisi kolay. Halı, koltuk ve perde yıkama.'}]}),component:Home})
const faqs:[string,string][]=[['Halı yıkama m² fiyatı ne kadar?','Halı yıkama ücreti 130 TL/m²’dir. 6 m² ve altındaki siparişlerde minimum ücret 780 TL olarak uygulanır.'],['Halı alım ve teslimat ücretsiz mi?','Evet. Hizmet bölgelerimizde halı alım ve teslimat servisi ücretsizdir.'],['Halılar ne zaman teslim edilir?','Genellikle 2 günde teslim edilir. Yoğun dönemlerde süre 2–3 güne çıkabilir.'],['Atabey ve Eğirdir’e hangi günler servis var?','Atabey, Eğirdir ve yakın köy güzergâhları Salı ve Cuma günleri planlanır. Adresinizi arayıp teyit edebilirsiniz.']]
function Home(){const [area,setArea]=useState('12');const sqm=Math.max(0,Number(area)||0);const price=sqm===0?0:sqm<=6?780:sqm*130;const faqSchema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))};const businessSchema={'@context':'https://schema.org','@type':'LocalBusiness','@id':'https://ispartaipekhaliyikama.com/#business',name:'İpek Halı Yıkama',url:'https://ispartaipekhaliyikama.com',telephone:'+90-246-242-99-99',image:'https://ispartaipekhaliyikama.com/wp-content/uploads/2024/11/isparta-ipek-logo.png',areaServed:[{'@type':'City',name:'Isparta'},{'@type':'AdministrativeArea',name:'Atabey'},{'@type':'AdministrativeArea',name:'Eğirdir'},{'@type':'AdministrativeArea',name:'Gönen'},...['Büyük Gökçeli','Küçük Gökçeli','Büyük Hacılar','Küçük Hacılar','Ali Köyü','Harmanören','Kuleönü','İslamköy'].map(name=>({'@type':'Place',name}))],hasOfferCatalog:{'@type':'OfferCatalog',name:'Yıkama hizmetleri',itemListElement:[{'@type':'Offer',itemOffered:{'@type':'Service',name:'Halı yıkama'},priceSpecification:{'@type':'UnitPriceSpecification',price:'130',priceCurrency:'TRY',unitText:'m²'}},{'@type':'Offer',itemOffered:{'@type':'Service',name:'Koltuk takımı yıkama'},price:'2500',priceCurrency:'TRY'}]}};return <>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(businessSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
<section className="ipek-home-hero"><div className="ipek-home-hero-inner"><div className="ipek-home-copy"><span className="ipek-home-kicker"><i className="kicker-spark"/> Isparta’da halı yıkama</span><h1 className="ipek-home-title">Halıya özen,<br/><span>eve ferahlık.</span></h1><p className="ipek-home-lede">Halılarınızı ücretsiz alıp adresinize teslim ediyoruz. Fiyatı baştan görün; alım gününü bize sorun.</p><div className="ipek-home-actions"><a className="button button-primary" href={PHONE}>Ara · 0246 242 99 99</a><a className="button button-quiet" href={WA} target="_blank" rel="noreferrer">WhatsApp’tan yazın ↗</a></div><div className="hero-small-note"><i className="note-dot"/> Halı yıkama <b>130 TL / m²</b> · minimum ücret 780 TL</div></div><div className="home-art home-photo-art" aria-label="Halı yıkama sahnesi ve fiyat bilgisi">
<div className="home-photo-frame"><img src={photos.factory} alt="Fırçaları ve taşıma bandıyla profesyonel halı yıkama makinesi" width="900" height="700" fetchPriority="high"/></div>

<div className="wash-stage-label"><span>03</span><b>HALIYA<br/>ÖZEN</b></div><div className="wash-price-float"><span>HALI YIKAMA · ISPARTA</span><strong>130 <small>TL / m²</small></strong><p>Minimum ücret 780 TL</p><a href="/hali-yikama#hesaplayici">Fiyatı hesapla <i>↗</i></a></div></div></div></section>
<div className="ipek-proofbar"><div className="ipek-proof-item"><strong>Ücretsiz servis</strong><span>Halı alım ve teslimatı</span></div><div className="ipek-proof-item"><strong>Net metrekare fiyatı</strong><span>130 TL / m² · minimum 780 TL</span></div><div className="ipek-proof-item"><strong>2–3 gün</strong><span>Yoğunluğa göre teslim süresi</span></div></div>
<div className="textile-ticker" aria-hidden="true"><div className="ticker-track"><span>TOZUNU AL</span><i>✳</i><span>HALIYI YIKA · DURULA</span><i>✳</i><span>KURUT · KONTROL ET</span><i>✳</i><span>ADRESE TESLİM</span><i>✳</i><span>TOZUNU AL</span><i>✳</i><span>HALIYI YIKA · DURULA</span><i>✳</i><span>KURUT · KONTROL ET</span><i>✳</i><span>ADRESE TESLİM</span><i>✳</i></div></div>
<section className="home-services"><div className="container"><SectionHead eyebrow="HİZMETLER" title="Evinizdeki tekstillere, ayrı ayrı özen." copy="Halı, koltuk, perde veya yorgan. İhtiyacınız olan hizmetin ayrıntılarına göz atın."/><div className="services-grid"><Service href="/hali-yikama" no="01" title="Halı yıkama" price="130 TL / m²" text="Ücretsiz kapıdan alım ve teslimat. Online hesaplayıcıyla yaklaşık ücreti görün."/><Service href="/koltuk-yikama" no="02" title="Koltuk yıkama" price="Takım 2.500 TL" text="Koltuk takımınız ve randevu planı için ayrıntıları öğrenin."/><Service href="/perde-yikama" no="03" title="Perde yıkama" price="Fiyat için bilgi alın" text="Perdenizin türünü ve ölçüsünü paylaşın; size güncel fiyatı bildirelim."/><Service href="/yorgan-battaniye-yikama" no="04" title="Yorgan & battaniye" price="Fiyat için bilgi alın" text="Yorgan ve battaniyeler için yıkama ve servis bilgisini sorun."/></div></div></section>
<section className="home-process"><div className="container process-layout"><SectionHead eyebrow="HALI YIKAMA SÜRECİ" title="Halı, temizlenip kapınıza dönene kadar." copy="Her halının yolculuğu kontrolden başlar; yıkama, kurutma ve son kontrolün ardından teslimatla tamamlanır."/><CarpetStages/></div></section>
<section className="home-area"><div className="container"><div className="home-area-heading"><SectionHead eyebrow="SERVİS ALANI" title="Isparta ve çevre güzergâhlar." copy="Atabey ve Eğirdir için Salı ve Cuma. Haritadaki diğer köy ve ilçe noktaları için adresinizi teyit edin."/><a className="button button-quiet" href="/hizmet-bolgeleri">Tüm servis bölgeleri ↗</a></div><ServiceAreaMap/></div></section>
<section className="home-faq"><div className="container faq-layout"><SectionHead eyebrow="MERAK EDİLENLER" title="Önce aklınızdaki sorular." copy="Fiyat, servis veya teslimatla ilgili başka bir sorunuz varsa bize sorun."/><div><FaqRows items={faqs}/><a className="button button-quiet" href="/sss" style={{marginTop:22}}>Tüm sorular ↗</a></div></div></section>
<section className="section"><div className="container"><div className="price-calculator"><div className="eyebrow"><span className="eyebrow-dot"/>HIZLI FİYAT TAHMİNİ</div><h2 style={{marginTop:13}}>Kaç m² halınız var?</h2><p style={{opacity:.75,marginTop:8}}>6 m² ve altı siparişlerde minimum 780 TL alınır.</p><div className="calculator-form"><label>Halı alanı (m²)<input type="number" min="1" step="0.5" value={area} onChange={e=>setArea(e.target.value)} aria-label="Halı alanı metrekare"/></label><a className="button button-white" href="/hali-yikama#hesaplayici">Detaylı hesapla ↗</a></div><div className="calc-result"><strong>{sqm===0?'—':`${new Intl.NumberFormat('tr-TR').format(price)} TL`}</strong><span>{sqm===0?'Tahmini tutarı görmek için metrekare girin':'yaklaşık yıkama ücreti · servis bölgesine göre teslimat ücretsiz'}</span></div></div></div></section>
<VideoGallery/>
<ContactBand title="Halılar için fiyat ve alım günü sorun." copy="Telefonla arayın veya WhatsApp’tan adresinizi gönderin; size uygun servis zamanını konuşalım."/>
</>}
function Service({href,no,title,price,text}:{href:string;no:string;title:string;price:string;text:string}){return <a className="service-card" href={href}><ServiceIllustration title={title}/><span className="service-index">{no} / İPEK</span><div><h3>{title}</h3><p>{text}</p></div><div className="service-bottom"><span>{price}</span><span>↗</span></div></a>}
function ServiceIllustration({title}:{title:string}){return <div className="service-art service-photo"><img src={servicePhoto(title)} alt={title+' hizmetine ait tekstil ve bakım fotoğrafı'} loading="lazy" width="640" height="420"/><span className="service-art-label">{title.toLocaleUpperCase('tr-TR')}</span></div>}
